---
name: docs

on:
  workflow_dispatch:
  push:
    branches:
    - main
    paths:
    - '.github/workflows/docs.yaml'
    - 'mkdocs.yaml'
    - 'docs/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout branch
      uses: actions/checkout@v2

    - name: Deploy docs
      uses: mhausenblas/mkdocs-deploy-gh-pages@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        CONFIG_FILE: mkdocs.yaml
        REQUIREMENTS: .github/workflows/requirements.txt
